apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-deployment
  namespace: default
  labels:
    app: logistics 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
        - name: logistics
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "100Mi"
            limits:
              cpu: "100m"     
              memory: "128Mi"    
              ephemeral-storage: "100Mi" 
      tolerations:
      - key: "autopilot.gke.io"
        operator: "Exists"
        effect: "NoSchedule"