apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-deployment
  labels:
    app: logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
      - name: logistics
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8080