apiVersion: v1
kind: Service
metadata:
  name: logistics-service
  namespace: default
spec:
  selector:
    app: logistics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer